/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: f072375b3646e3fb8dcb2b052afef002)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/backend/index");
		durableNamespaces: "PlannerAgent" | "Supervisor" | "PrinterHub" | "SpotifyAgent" | "EmailAgent" | "SpotifyOAuthStore" | "MotivationalAgent" | "SpotifySyncHub";
	}
	interface Env {
		KV: KVNamespace;
		KV_CONFIGS: KVNamespace;
		DB: D1Database;
		VECTORIZE_LOGS: VectorizeIndex;
		GITHUB_TOKEN: SecretsStoreSecret;
		CLOUDFLARE_API_TOKEN: SecretsStoreSecret;
		OPENAI_API_KEY: SecretsStoreSecret;
		CLOUDFLARE_ACCOUNT_ID: SecretsStoreSecret;
		CLOUDFLARE_SECRETS_STORE_TOKEN: SecretsStoreSecret;
		WORKER_API_KEY: SecretsStoreSecret;
		AI_GATEWAY_TOKEN: SecretsStoreSecret;
		CF_BROWSER_RENDER_TOKEN: SecretsStoreSecret;
		JULES_API_KEY: SecretsStoreSecret;
		GEMINI_API_KEY: SecretsStoreSecret;
		ANTHROPIC_API_KEY: SecretsStoreSecret;
		CLOUDFLARE_AI_SEARCH_TOKEN: SecretsStoreSecret;
		AGENTIC_WORKER_API_KEY: SecretsStoreSecret;
		SPOTIFY_CLIENT_ID: SecretsStoreSecret;
		SPOTIFY_CLIENT_SECRET: SecretsStoreSecret;
		PRINTER_VPC: Fetcher;
		AI: Ai;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		HEALTH_SANDBOX_TIMEOUT_MS: 15000;
		USE_OPENAI_MODELS: true;
		MAX_AI_BUDGET: 150;
		AI_GATEWAY_NAME: "default-gateway";
		WORKER_NAME: "dopamine";
		PLANNER: DurableObjectNamespace<import("./src/backend/index").PlannerAgent>;
		SUPERVISOR: DurableObjectNamespace<import("./src/backend/index").Supervisor>;
		PRINTER_HUB: DurableObjectNamespace<import("./src/backend/index").PrinterHub>;
		SPOTIFY_AGENT: DurableObjectNamespace<import("./src/backend/index").SpotifyAgent>;
		EMAIL_AGENT: DurableObjectNamespace<import("./src/backend/index").EmailAgent>;
		SPOTIFY_OAUTH_STORE: DurableObjectNamespace<import("./src/backend/index").SpotifyOAuthStore>;
		MOTIVATIONAL_AGENT: DurableObjectNamespace<import("./src/backend/index").MotivationalAgent>;
		SPOTIFY_SYNC_HUB: DurableObjectNamespace<import("./src/backend/index").SpotifySyncHub>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HEALTH_SANDBOX_TIMEOUT_MS" | "USE_OPENAI_MODELS" | "MAX_AI_BUDGET" | "AI_GATEWAY_NAME" | "WORKER_NAME">> {}
}
