/**
 * DO NOT DEFINE Env HERE.
 *
 * The canonical `Env` interface is auto-generated by `wrangler types`,
 * which writes `worker-configuration.d.ts` at the project root.
 * That file is registered as a global type in `tsconfig.json` under:
 *
 *   "types": ["./worker-configuration.d.ts"]
 *
 * This makes `Env` globally available in all TypeScript files without
 * any import. Manually defining it here would conflict and break the build.
 *
 * To add or update bindings, edit `wrangler.jsonc` and then run:
 *   pnpm wrangler types
 */

export {};
